/*^^^^^^^^^^^^^^ INFINITY NORM TEST ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Testing infinity norm errors of rocRhoPimple.
In the main tests, codes run till time=0.1s, and then data are saved.
A pre-calculated data for the same time has already been save in the
data folder for bench-marking. For ease of implementation, the folder
name is choden to be 0.11 just to make a distinction from the one
that is supposed to be generated by the test cases. The generated
and benchmarching data are then subtracted and the maximum value of
a particular field (infinity norm) is returned. This test is only
performed forrocRhoPimple in serail mode, but can be extended,
if required.
*/

#include "rocRhoPimple.H"
#include "gtest.h"

char** ARGV;
int ARGC;

// Test fixture which tests COM. Derived from the Google test primer
class regressionTest : public ::testing::Test
{
protected:
    void SetUp() {};

    void TearDown() {};
    
    comFoam *regTest;
};


TEST_F(regressionTest, regression)
{
    std::stringstream ss;
    std::stringstream caseI;
    std::stringstream caseII;

    std::string word;

    if (ARGC > 1)
    {
        for (int i=1; i<ARGC; ++i)
        {
            ss.clear();
            ss.str("");
            ss << ARGV[i];
            
            if (ss.str() == "-case")
            {
                caseI << ARGV[i+1] ;
            }
        }
    }
    char* solverType = const_cast<char *>("rocRhoPimple");

    constexpr int ARGC1 = 3;
    char *ARGV1[ARGC1];
    ARGV1[0] = solverType; //ARGV[0];
    ARGV1[1] = const_cast<char *>("-case");

    word = caseI.str();
    int length = word.length();
    char *tmpCaseI = new char[length+1];

    strcpy(tmpCaseI, word.c_str());
    ARGV1[2] = tmpCaseI;

    
    if (solverType == const_cast<char *>("rocRhoPimple"))
    {
        regTest = new rhoPimple();
    }
    
    regTest->errorEvaluate(ARGC1, ARGV1);
    //EXPECT_LE(regTest->testStat, 1e-10)
    EXPECT_LE(regTest->testStat, 10) << "Testing " << solverType <<": regression unsuccessful"
                                        << std::endl;
    delete regTest; regTest=NULL;
    delete [] tmpCaseI;
}



int main(int argc, char *argv[])
{
    ::testing::InitGoogleTest(&argc, argv);
    ARGC = argc;
    ARGV = argv;
    return RUN_ALL_TESTS();
}
